// Chain configurations for ChainLens - Multi-chain Transaction Explorer

export type ApiStatus = 'free' | 'rate_limited' | 'key_required' | 'key_optional';

export interface ChainConfig {
  id: string;
  name: string;
  symbol: string;
  icon: string;
  color: string;
  explorerUrl: string;
  apiEndpoint: string;
  fallbackEndpoints?: string[];
  apiType: 'etherscan' | 'blockscout' | 'subscan' | 'solscan' | 'mintscan' | 'custom';
  decimals: number;
  addressRegex: RegExp;
  category: 'evm' | 'substrate' | 'cosmos' | 'solana' | 'move' | 'other';
  enabled: boolean;
  apiStatus: ApiStatus;
  apiKeyEnvVar?: string;
  rateLimitInfo?: string;
}

export const CHAINS: ChainConfig[] = [
  // EVM Chains
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    icon: '\u27e0',
    color: 'hsl(220, 75%, 55%)',
    explorerUrl: 'https://etherscan.io',
    apiEndpoint: 'https://api.etherscan.io/api',
    fallbackEndpoints: ['https://eth.blockscout.com/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_ETHERSCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key, 100k/day with free key',
  },
  {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'MATIC',
    icon: '\u2b21',
    color: 'hsl(265, 85%, 55%)',
    explorerUrl: 'https://polygonscan.com',
    apiEndpoint: 'https://api.polygonscan.com/api',
    fallbackEndpoints: ['https://polygon.blockscout.com/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_POLYGONSCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    symbol: 'ETH',
    icon: '\u25c8',
    color: 'hsl(210, 80%, 55%)',
    explorerUrl: 'https://arbiscan.io',
    apiEndpoint: 'https://api.arbiscan.io/api',
    fallbackEndpoints: ['https://arbitrum.blockscout.com/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_ARBISCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'ETH',
    icon: '\u2b22',
    color: 'hsl(0, 70%, 55%)',
    explorerUrl: 'https://optimistic.etherscan.io',
    apiEndpoint: 'https://api-optimistic.etherscan.io/api',
    fallbackEndpoints: ['https://optimism.blockscout.com/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_OPTIMISM_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'base',
    name: 'Base',
    symbol: 'ETH',
    icon: '\u25ce',
    color: 'hsl(215, 90%, 55%)',
    explorerUrl: 'https://basescan.org',
    apiEndpoint: 'https://api.basescan.org/api',
    fallbackEndpoints: ['https://base.blockscout.com/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_BASESCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    symbol: 'AVAX',
    icon: '\u25b2',
    color: 'hsl(0, 75%, 55%)',
    explorerUrl: 'https://snowtrace.io',
    apiEndpoint: 'https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan/api',
    fallbackEndpoints: ['https://api.snowtrace.io/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public API via Routescan',
  },
  {
    id: 'bsc',
    name: 'BNB Chain',
    symbol: 'BNB',
    icon: '\u25c6',
    color: 'hsl(45, 90%, 50%)',
    explorerUrl: 'https://bscscan.com',
    apiEndpoint: 'https://api.bscscan.com/api',
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_BSCSCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'ronin',
    name: 'Ronin',
    symbol: 'RON',
    icon: '\u2694',
    color: 'hsl(200, 75%, 55%)',
    explorerUrl: 'https://app.roninchain.com',
    apiEndpoint: 'https://skynet-api.roninchain.com/ronin/explorer/v2/api',
    apiType: 'custom',
    decimals: 18,
    addressRegex: /^(0x|ronin:)[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: false,
    apiStatus: 'key_required',
    rateLimitInfo: 'API not publicly available',
  },
  {
    id: 'fantom',
    name: 'Fantom',
    symbol: 'FTM',
    icon: '\ud83d\udc7b',
    color: 'hsl(210, 85%, 55%)',
    explorerUrl: 'https://ftmscan.com',
    apiEndpoint: 'https://api.ftmscan.com/api',
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_FTMSCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'gnosis',
    name: 'Gnosis',
    symbol: 'xDAI',
    icon: '\ud83e\udd89',
    color: 'hsl(160, 60%, 45%)',
    explorerUrl: 'https://gnosisscan.io',
    apiEndpoint: 'https://api.gnosisscan.io/api',
    fallbackEndpoints: ['https://gnosis.blockscout.com/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_GNOSISSCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'linea',
    name: 'Linea',
    symbol: 'ETH',
    icon: '\u2501',
    color: 'hsl(225, 70%, 55%)',
    explorerUrl: 'https://lineascan.build',
    apiEndpoint: 'https://api.lineascan.build/api',
    fallbackEndpoints: ['https://linea.blockscout.com/api'],
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'key_optional',
    apiKeyEnvVar: 'VITE_LINEASCAN_API_KEY',
    rateLimitInfo: '5 calls/sec without key',
  },
  {
    id: 'zksync',
    name: 'zkSync Era',
    symbol: 'ETH',
    icon: '\u2b26',
    color: 'hsl(255, 70%, 60%)',
    explorerUrl: 'https://explorer.zksync.io',
    apiEndpoint: 'https://block-explorer-api.mainnet.zksync.io/api',
    apiType: 'etherscan',
    decimals: 18,
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    category: 'evm',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public API',
  },
  // Substrate/Polkadot Chains
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'DOT',
    icon: '\u25cf',
    color: 'hsl(340, 80%, 55%)',
    explorerUrl: 'https://polkadot.subscan.io',
    apiEndpoint: 'https://polkadot.api.subscan.io',
    apiType: 'subscan',
    decimals: 10,
    addressRegex: /^[1-9A-HJ-NP-Za-km-z]{47,48}$/,
    category: 'substrate',
    enabled: true,
    apiStatus: 'rate_limited',
    apiKeyEnvVar: 'VITE_SUBSCAN_API_KEY',
    rateLimitInfo: '30 calls/min free, more with API key',
  },
  {
    id: 'kusama',
    name: 'Kusama',
    symbol: 'KSM',
    icon: '\u25c9',
    color: 'hsl(0, 0%, 30%)',
    explorerUrl: 'https://kusama.subscan.io',
    apiEndpoint: 'https://kusama.api.subscan.io',
    apiType: 'subscan',
    decimals: 12,
    addressRegex: /^[1-9A-HJ-NP-Za-km-z]{47,48}$/,
    category: 'substrate',
    enabled: true,
    apiStatus: 'rate_limited',
    apiKeyEnvVar: 'VITE_SUBSCAN_API_KEY',
    rateLimitInfo: '30 calls/min free, more with API key',
  },
  // Bittensor
  {
    id: 'bittensor',
    name: 'Bittensor',
    symbol: 'TAO',
    icon: '\ud83e\udde0',
    color: 'hsl(45, 90%, 55%)',
    explorerUrl: 'https://taostats.io',
    apiEndpoint: 'https://bittensor.api.subscan.io',
    apiType: 'subscan',
    decimals: 9,
    addressRegex: /^5[a-zA-Z0-9]{47}$/,
    category: 'substrate',
    enabled: true,
    apiStatus: 'rate_limited',
    apiKeyEnvVar: 'VITE_SUBSCAN_API_KEY',
    rateLimitInfo: '30 calls/min free, more with API key',
  },
  // Vara Network
  {
    id: 'vara',
    name: 'Vara Network',
    symbol: 'VARA',
    icon: '\u2699',
    color: 'hsl(150, 70%, 50%)',
    explorerUrl: 'https://vara.subscan.io',
    apiEndpoint: 'https://vara.api.subscan.io',
    apiType: 'subscan',
    decimals: 12,
    addressRegex: /^[1-9A-HJ-NP-Za-km-z]{47,48}$/,
    category: 'substrate',
    enabled: true,
    apiStatus: 'rate_limited',
    apiKeyEnvVar: 'VITE_SUBSCAN_API_KEY',
    rateLimitInfo: '30 calls/min free, more with API key',
  },
  // Cosmos Chains
  {
    id: 'osmosis',
    name: 'Osmosis',
    symbol: 'OSMO',
    icon: '\ud83e\uddea',
    color: 'hsl(265, 70%, 55%)',
    explorerUrl: 'https://www.mintscan.io/osmosis',
    apiEndpoint: 'https://lcd.osmosis.zone',
    fallbackEndpoints: ['https://osmosis-lcd.quickapi.com'],
    apiType: 'mintscan',
    decimals: 6,
    addressRegex: /^osmo1[a-z0-9]{38}$/,
    category: 'cosmos',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public LCD endpoint',
  },
  {
    id: 'cosmos',
    name: 'Cosmos Hub',
    symbol: 'ATOM',
    icon: '\u269b',
    color: 'hsl(265, 70%, 55%)',
    explorerUrl: 'https://www.mintscan.io/cosmos',
    apiEndpoint: 'https://lcd-cosmoshub.keplr.app',
    fallbackEndpoints: ['https://cosmos-lcd.quickapi.com', 'https://cosmoshub.lava.build'],
    apiType: 'mintscan',
    decimals: 6,
    addressRegex: /^cosmos1[a-z0-9]{38}$/,
    category: 'cosmos',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public LCD endpoint',
  },
  {
    id: 'celestia',
    name: 'Celestia',
    symbol: 'TIA',
    icon: '\u2600',
    color: 'hsl(270, 75%, 60%)',
    explorerUrl: 'https://www.mintscan.io/celestia',
    apiEndpoint: 'https://celestia-lcd.publicnode.com',
    fallbackEndpoints: ['https://celestia.lava.build'],
    apiType: 'mintscan',
    decimals: 6,
    addressRegex: /^celestia1[a-z0-9]{38}$/,
    category: 'cosmos',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public LCD endpoint',
  },
  {
    id: 'injective',
    name: 'Injective',
    symbol: 'INJ',
    icon: '\ud83d\udc89',
    color: 'hsl(175, 80%, 50%)',
    explorerUrl: 'https://www.mintscan.io/injective',
    apiEndpoint: 'https://lcd.injective.network',
    fallbackEndpoints: ['https://injective-lcd.publicnode.com'],
    apiType: 'mintscan',
    decimals: 18,
    addressRegex: /^inj1[a-z0-9]{38}$/,
    category: 'cosmos',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public LCD endpoint',
  },
  // Solana
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    icon: '\u25d0',
    color: 'hsl(280, 75%, 60%)',
    explorerUrl: 'https://solscan.io',
    apiEndpoint: 'https://api.solscan.io',
    apiType: 'solscan',
    decimals: 9,
    addressRegex: /^[1-9A-HJ-NP-Za-km-z]{32,44}$/,
    category: 'solana',
    enabled: true,
    apiStatus: 'key_required',
    apiKeyEnvVar: 'VITE_HELIUS_API_KEY',
    rateLimitInfo: 'Requires Helius API key (free tier available at helius.dev)',
  },
  // Move-based Chains
  {
    id: 'sui',
    name: 'Sui',
    symbol: 'SUI',
    icon: '\ud83d\udca7',
    color: 'hsl(205, 85%, 55%)',
    explorerUrl: 'https://suiscan.xyz',
    apiEndpoint: 'https://fullnode.mainnet.sui.io',
    fallbackEndpoints: ['https://sui-mainnet.public.blastapi.io'],
    apiType: 'custom',
    decimals: 9,
    addressRegex: /^0x[a-fA-F0-9]{64}$/,
    category: 'move',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public RPC endpoint',
  },
  {
    id: 'aptos',
    name: 'Aptos',
    symbol: 'APT',
    icon: '\ud83c\udf00',
    color: 'hsl(160, 70%, 50%)',
    explorerUrl: 'https://explorer.aptoslabs.com',
    apiEndpoint: 'https://fullnode.mainnet.aptoslabs.com/v1',
    fallbackEndpoints: ['https://aptos-mainnet.public.blastapi.io/v1'],
    apiType: 'custom',
    decimals: 8,
    addressRegex: /^0x[a-fA-F0-9]{64}$/,
    category: 'move',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public REST API',
  },
  // Other Chains
  {
    id: 'near',
    name: 'NEAR',
    symbol: 'NEAR',
    icon: '\u25ef',
    color: 'hsl(175, 70%, 50%)',
    explorerUrl: 'https://nearblocks.io',
    apiEndpoint: 'https://api.nearblocks.io/v1',
    apiType: 'custom',
    decimals: 24,
    addressRegex: /^[a-z0-9._-]+$/,
    category: 'other',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public API',
  },
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    icon: '\u20bf',
    color: 'hsl(35, 90%, 55%)',
    explorerUrl: 'https://blockchair.com/bitcoin',
    apiEndpoint: 'https://blockchain.info',
    fallbackEndpoints: ['https://blockstream.info/api'],
    apiType: 'custom',
    decimals: 8,
    addressRegex: /^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,62}$/,
    category: 'other',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public API (rate limited)',
  },
  {
    id: 'tron',
    name: 'Tron',
    symbol: 'TRX',
    icon: '\u27c1',
    color: 'hsl(0, 80%, 50%)',
    explorerUrl: 'https://tronscan.org',
    apiEndpoint: 'https://apilist.tronscanapi.com/api',
    apiType: 'custom',
    decimals: 6,
    addressRegex: /^T[a-zA-Z0-9]{33}$/,
    category: 'other',
    enabled: true,
    apiStatus: 'free',
    rateLimitInfo: 'Free public API',
  },
];

export const getChainById = (id: string): ChainConfig | undefined => {
  return CHAINS.find(chain => chain.id === id);
};

export const getEnabledChains = (): ChainConfig[] => {
  return CHAINS.filter(chain => chain.enabled);
};

export const getChainsByCategory = (category: ChainConfig['category']): ChainConfig[] => {
  return CHAINS.filter(chain => chain.category === category && chain.enabled);
};

export const detectChainFromAddress = (address: string): ChainConfig[] => {
  return CHAINS.filter(chain => chain.enabled && chain.addressRegex.test(address));
};

export const getChainsByApiStatus = (status: ApiStatus): ChainConfig[] => {
  return CHAINS.filter(chain => chain.enabled && chain.apiStatus === status);
};

export const CHAIN_CATEGORIES = [
  { id: 'evm', name: 'EVM Chains', description: 'Ethereum Virtual Machine compatible' },
  { id: 'substrate', name: 'Substrate', description: 'Polkadot ecosystem' },
  { id: 'cosmos', name: 'Cosmos', description: 'Cosmos SDK chains' },
  { id: 'solana', name: 'Solana', description: 'Solana ecosystem' },
  { id: 'move', name: 'Move', description: 'Move-based chains' },
  { id: 'other', name: 'Other', description: 'Other blockchain networks' },
] as const;

export const API_STATUS_INFO = {
  free: {
    label: 'Free',
    description: 'Fully free public API with generous limits',
    color: 'hsl(142, 70%, 45%)',
  },
  rate_limited: {
    label: 'Rate Limited',
    description: 'Free but with strict rate limits',
    color: 'hsl(45, 90%, 50%)',
  },
  key_optional: {
    label: 'Key Optional',
    description: 'Works without key but better with one',
    color: 'hsl(200, 70%, 50%)',
  },
  key_required: {
    label: 'Key Required',
    description: 'Requires API key to function',
    color: 'hsl(0, 70%, 55%)',
  },
} as const;
